# file name can be typeDefs.graphql or just typeDefs.gql
# username: String! @unique — type string, ! - required, @unique - unique

type User {
  _id: ID
  username: String! @unique
  email: String! @unique
  password: String!
  avatar: String
  joinDate: String
  favorites: [Post]
}

type Post {
  _id: ID
  title: String!
  imageUrl: String!
  categories: [String]!
  description: String!
  createDate: String
  likes: Int
  createdBy: User!
  messages: [Message]
}

type Message {
  _id: ID
  messageBody: String!
  messageDate: String
  messageUser: User!
}

type Query {
  getPosts: [Post]
}

type Mutation {
  addPost(title: String!, imageUrl: String!, categories: [String]!, description: String!, createdBy: ID!): Post!
  signinUser(username: String!, password: String!): User!
  signupUser(username: String!, email: String!, password: String!): User!
}
